#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: "vsphere"
monitoring:
  grafana:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
    secret:
      admin_password: YWRtaW4=
      admin_user: YWRtaW4=
    ingress:
     enabled: true
     virtual_host_fqdn: grafana.caas.pez.pivotal.io
  grafana_init_container:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
  grafana_sc_dashboard:
    image:
      repository: "projects.registry.vmware.com/tkg/grafana"
