apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-for-kubernetes-leader-election-role
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mysql-for-kubernetes-backup-sidecar-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackuplocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackups
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackups/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mysql-for-kubernetes-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackuplocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackupschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-for-kubernetes-tanzumysqlbackup-creator-role
rules:
- apiGroups:
  - mysql.tanzu.vmware.com
  resources:
  - tanzumysqlbackups
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-for-kubernetes-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-for-kubernetes-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-for-kubernetes-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-for-kubernetes-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'
