---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnetapp
  name: aspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
      name: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        imagePullPolicy: IfNotPresent
        image: harbor.tkgi.caas.pez.pivotal.io/windows/aspnet:4.8 #10.193.39.199/windows/samples:aspnetapp
      imagePullSecrets:
      - name: harbor
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  ports:
  - port: 80
  selector:
    app: aspnetapp
  type: LoadBalancer
