imagePullSecret: harbor
operatorImage: "harbor.ragazzilab.com/tanzu-sql/tanzu-mysql-operator:0.2.0"
tanzuMySQLImage: "harbor.ragazzilab.com/tanzu-sql/tanzu-mysql-instance:0.2.0"
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi
