#@data/values
#@overlay/match-child-defaults missing_ok=True
---
externalDns:
  image:
    repository: projects.registry.vmware.com/tkg
  deployment:
    #@overlay/replace
    args:
    - --txt-owner-id=k8s-monitoring
    - --provider=rfc2136
    - --rfc2136-host=192.168.100.50 #! IP of RFC2136 compatible dns server
    - --rfc2136-port=53
    - --rfc2136-zone=ragazzilab.com #! zone where services are deployed
    - --rfc2136-insecure
    - --rfc2136-tsig-axfr
    - --source=service
    - --domain-filter=ragazzilab.com #! zone where services are deployed
