#@data/values
#@overlay/match-child-defaults missing_ok=True
---
logging:
  image:
    repository: projects.registry.vmware.com/tkg
tkg:
  instance_name: "WORK"
  cluster_name: "monitoring"
fluent_bit:
  output_plugin: "syslog"
  syslog:
    host: "syslog.caas.pez.pivotal.io"
    port: "514"
    mode: "udp"
    format: "rfc5424"
audit_logging:
  kube_apiserver: true
  auditd: true
