kind: Service
apiVersion: v1
metadata:
  name: gangwaysvc
  namespace: tanzu-system-auth
  labels:
    app: gangway
spec:
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: "http"
      nodePort: 30166
  selector:
    app: gangway
