properties-configuration:
  iaas_configuration:
    name: ((vcenter_hostname))
    vcenter_host: ((vcenter_hostname))
    vcenter_username: ((vcenter_userid))
    vcenter_password: ((vcenter_password))
    datacenter: ((vsphere_datacenter))
    ssl_verification_enabled: false
    disk_type: thin
    ephemeral_datastores_string: ((vsphere_datastore))
    persistent_datastores_string: ((vsphere_datastore))
    bosh_vm_folder: ((vsphere_vms_folder))
    bosh_template_folder: ((vsphere_templates_folder))
    bosh_disk_path: ((vsphere_disks_folder))
    nsx_networking_enabled: false # disable for Windows
    nsx_mode: nsx-t
    #nsx_address: ((nsx_hostname))
    #nsx_username: ((nsx_admin_user))
    #nsx_password: ((nsx_admin_password))
    #nsx_ca_certificate: ((nsx_ca_cert))
  director_configuration:
    ntp_servers_string: ((ntp))
    resurrector_enabled: true
    post_deploy_enabled: ((post_deploy_enabled))
    max_threads: ((max_threads))
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: ((bosh_trusted_certs))
  syslog_configuration:
    address: ((syslog_address))
    enabled: true
    port: ((syslog_port))
    tls_enabled: false
    transport_protocol: ((syslog_protocol))
az-configuration:
- name: MGMT
  clusters:
  - cluster: ((vsphere_mgmtaz_cluster))
    resource_pool: ((vsphere_mgmtaz_resource_pool))
    host_group: ((vsphere_mgmtaz_host_group))
- name: AZ1
  clusters:
  - cluster: ((vsphere_az1_cluster))
    resource_pool: ((vsphere_az1_resource_pool))
    host_group: ((vsphere_az1_host_group))
- name: AZ2
  clusters:
  - cluster: ((vsphere_az2_cluster))
    resource_pool: ((vsphere_az2_resource_pool))
    host_group: ((vsphere_az2_host_group))
- name: AZ3
  clusters:
  - cluster: ((vsphere_az3_cluster))
    resource_pool: ((vsphere_az3_resource_pool))
    host_group: ((vsphere_az3_host_group))
network-assignment:
  singleton_availability_zone:
    name: MGMT
  network:
    name: PKS-MGMT
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: PKS-MGMT
    subnets:
    - iaas_identifier: ((pks_mgmt_network))
      cidr: ((pks_mgmt_network_cidr))
      reserved_ip_ranges: ((pks_mgmt_network_reserved))
      dns: ((dns))
      gateway: ((pks_mgmt_gateway))
      availability_zone_names:
      - MGMT
      - AZ1
      - AZ2
      - AZ3
vmextensions-configuration: []
